<?php
declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

/**
 * Stubs for Magento generated/unavailable classes.
 *
 * CollectionFactory classes are generated by bin/magento setup:di:compile and do
 * not exist in the source package. Define minimal stubs here so PHPUnit can
 * create mocks of them without a full Magento installation.
 */
if (!class_exists(\Magento\Indexer\Model\Indexer\CollectionFactory::class)) {
    // phpcs:ignore
    class_alias(
        \Stratum\DevHealthCheck\Test\Stub\IndexerCollectionFactoryStub::class,
        \Magento\Indexer\Model\Indexer\CollectionFactory::class,
    );
}
